import "../styles/index.scss";
import ReduxProvider from "./store/ReduxProvider";
import { Toast } from "./toast";
import Head from 'next/head';
import { Nunito } from 'next/font/google'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Add additional meta tags as needed */}
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"/>
        <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests" />
      </Head>
      <html lang="en" className={nunito.className}>
        <body>
          <ReduxProvider>
            {/* <Header /> */}
            {children}
            {/* <Footer /> */}
            <Toast />
          </ReduxProvider>
        </body>
      </html>
    </>
  );
}
